function Email() {};

Email.create = function(verifyModel) {
	var strVar="";
	strVar += "<!DOCTYPE html PUBLIC \"-\/\/W3C\/\/DTD XHTML 1.0 Transitional \/\/EN\" \"http:\/\/www.w3.org\/TR\/xhtml1\/DTD\/xhtml1-transitional.dtd\">";
	strVar += "<html><head>";
	strVar += "    <title><\/title>";
	strVar += "    <meta http-equiv=\"Content-Type\" content=\"text\/html; charset=utf-8\">";
	strVar += "    <style type=\"text\/css\">";
	strVar += "body {";
	strVar += "  margin: 0;";
	strVar += "  mso-line-height-rule: exactly;";
	strVar += "  padding: 0;";
	strVar += "  min-width: 100%;";
	strVar += "}";
	strVar += "table {";
	strVar += "  border-collapse: collapse;";
	strVar += "  border-spacing: 0;";
	strVar += "}";
	strVar += "td {";
	strVar += "  padding: 0;";
	strVar += "  vertical-align: top;";
	strVar += "}";
	strVar += ".spacer,";
	strVar += ".border {";
	strVar += "  font-size: 1px;";
	strVar += "  line-height: 1px;";
	strVar += "}";
	strVar += ".spacer {";
	strVar += "  width: 100%;";
	strVar += "}";
	strVar += "img {";
	strVar += "  border: 0;";
	strVar += "  -ms-interpolation-mode: bicubic;";
	strVar += "}";
	strVar += ".image {";
	strVar += "  font-size: 12px;";
	strVar += "  Margin-bottom: 25px;";
	strVar += "  mso-line-height-rule: at-least;";
	strVar += "}";
	strVar += ".image img {";
	strVar += "  display: block;";
	strVar += "}";
	strVar += ".logo {";
	strVar += "  mso-line-height-rule: at-least;";
	strVar += "}";
	strVar += ".logo img {";
	strVar += "  display: block;";
	strVar += "}";
	strVar += "strong {";
	strVar += "  font-weight: bold;";
	strVar += "}";
	strVar += "h1,";
	strVar += "h2,";
	strVar += "h3,";
	strVar += "p,";
	strVar += "ol,";
	strVar += "ul,";
	strVar += "li {";
	strVar += "  Margin-top: 0;";
	strVar += "}";
	strVar += "ol,";
	strVar += "ul,";
	strVar += "li {";
	strVar += "  padding-left: 0;";
	strVar += "}";
	strVar += "blockquote {";
	strVar += "  Margin-top: 0;";
	strVar += "  Margin-right: 0;";
	strVar += "  Margin-bottom: 0;";
	strVar += "  padding-right: 0;";
	strVar += "}";
	strVar += ".column-top {";
	strVar += "  font-size: 60px;";
	strVar += "  line-height: 60px;";
	strVar += "}";
	strVar += ".column-bottom {";
	strVar += "  font-size: 34px;";
	strVar += "  line-height: 34px;";
	strVar += "}";
	strVar += ".column {";
	strVar += "  text-align: left;";
	strVar += "}";
	strVar += ".contents {";
	strVar += "  table-layout: fixed;";
	strVar += "  width: 100%;";
	strVar += "}";
	strVar += ".padded {";
	strVar += "  padding-left: 60px;";
	strVar += "  padding-right: 60px;";
	strVar += "  word-break: break-word;";
	strVar += "  word-wrap: break-word;";
	strVar += "}";
	strVar += ".wrapper {";
	strVar += "  display: table;";
	strVar += "  table-layout: fixed;";
	strVar += "  width: 100%;";
	strVar += "  min-width: 620px;";
	strVar += "  -webkit-text-size-adjust: 100%;";
	strVar += "  -ms-text-size-adjust: 100%;";
	strVar += "}";
	strVar += "table.wrapper {";
	strVar += "  table-layout: fixed;";
	strVar += "}";
	strVar += ".one-col,";
	strVar += ".two-col,";
	strVar += ".three-col {";
	strVar += "  Margin-left: auto;";
	strVar += "  Margin-right: auto;";
	strVar += "  width: 600px;";
	strVar += "}";
	strVar += ".centered {";
	strVar += "  Margin-left: auto;";
	strVar += "  Margin-right: auto;";
	strVar += "}";
	strVar += ".two-col .image {";
	strVar += "  Margin-bottom: 23px;";
	strVar += "}";
	strVar += ".two-col .column-bottom {";
	strVar += "  font-size: 37px;";
	strVar += "  line-height: 37px;";
	strVar += "}";
	strVar += ".two-col .column {";
	strVar += "  width: 300px;";
	strVar += "}";
	strVar += ".two-col .first .padded {";
	strVar += "  padding-left: 60px;";
	strVar += "  padding-right: 30px;";
	strVar += "}";
	strVar += ".two-col .second .padded {";
	strVar += "  padding-left: 30px;";
	strVar += "  padding-right: 60px;";
	strVar += "}";
	strVar += ".three-col .image {";
	strVar += "  Margin-bottom: 21px;";
	strVar += "}";
	strVar += ".three-col .column-bottom {";
	strVar += "  font-size: 39px;";
	strVar += "  line-height: 39px;";
	strVar += "}";
	strVar += ".three-col .column {";
	strVar += "  width: 200px;";
	strVar += "}";
	strVar += ".three-col .first .padded {";
	strVar += "  padding-left: 60px;";
	strVar += "  padding-right: 0;";
	strVar += "}";
	strVar += ".three-col .second .padded {";
	strVar += "  padding-left: 30px;";
	strVar += "  padding-right: 30px;";
	strVar += "}";
	strVar += ".three-col .third .padded {";
	strVar += "  padding-left: 0;";
	strVar += "  padding-right: 60px;";
	strVar += "}";
	strVar += "@media only screen and (min-width: 0) {";
	strVar += "  .wrapper {";
	strVar += "    text-rendering: optimizeLegibility;";
	strVar += "  }";
	strVar += "}";
	strVar += "@media only screen and (max-width: 620px) {";
	strVar += "  [class=wrapper] {";
	strVar += "    min-width: 320px !important;";
	strVar += "    width: 100% !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .one-col,";
	strVar += "  [class=wrapper] .two-col,";
	strVar += "  [class=wrapper] .three-col {";
	strVar += "    width: 320px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .column,";
	strVar += "  [class=wrapper] .gutter {";
	strVar += "    display: block;";
	strVar += "    float: left;";
	strVar += "    width: 320px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .padded {";
	strVar += "    padding-left: 30px !important;";
	strVar += "    padding-right: 30px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .block {";
	strVar += "    display: block !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .hide {";
	strVar += "    display: none !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .image {";
	strVar += "    margin-bottom: 25px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .image img {";
	strVar += "    height: auto !important;";
	strVar += "    width: 100% !important;";
	strVar += "  }";
	strVar += "}";
	strVar += ".wrapper h1 {";
	strVar += "  font-weight: 400;";
	strVar += "}";
	strVar += ".wrapper h2 {";
	strVar += "  font-weight: 400;";
	strVar += "}";
	strVar += ".wrapper h3 {";
	strVar += "  font-weight: bold;";
	strVar += "}";
	strVar += ".wrapper p,";
	strVar += ".wrapper ol,";
	strVar += ".wrapper ul {";
	strVar += "  font-weight: 400;";
	strVar += "}";
	strVar += ".wrapper blockquote p,";
	strVar += ".wrapper blockquote ol,";
	strVar += ".wrapper blockquote ul {";
	strVar += "  font-style: italic;";
	strVar += "  font-weight: 500;";
	strVar += "}";
	strVar += ".wrapper .column table:nth-last-child(2) td h1:last-child,";
	strVar += ".wrapper .column table:nth-last-child(2) td h2:last-child,";
	strVar += ".wrapper .column table:nth-last-child(2) td h3:last-child,";
	strVar += ".wrapper .column table:nth-last-child(2) td p:last-child,";
	strVar += ".wrapper .column table:nth-last-child(2) td ol:last-child,";
	strVar += ".wrapper .column table:nth-last-child(2) td ul:last-child {";
	strVar += "  Margin-bottom: 25px;";
	strVar += "}";
	strVar += ".wrapper a {";
	strVar += "  transition: all .2s;";
	strVar += "}";
	strVar += ".wrapper .preheader,";
	strVar += ".wrapper .header,";
	strVar += ".wrapper .footer,";
	strVar += ".wrapper .feature {";
	strVar += "  Margin-left: auto;";
	strVar += "  Margin-right: auto;";
	strVar += "}";
	strVar += ".wrapper .one-col,";
	strVar += ".wrapper .two-col,";
	strVar += ".wrapper .three-col {";
	strVar += "  background-color: #ffffff;";
	strVar += "  border-radius: 4px;";
	strVar += "  box-shadow: 0 1px 0 rgba(0, 0, 0, 0.1);";
	strVar += "  table-layout: fixed;";
	strVar += "}";
	strVar += ".wrapper center.divider {";
	strVar += "  Margin-bottom: 25px;";
	strVar += "}";
	strVar += ".wrapper center.divider img {";
	strVar += "  display: block;";
	strVar += "  Margin-left: auto;";
	strVar += "  Margin-right: auto;";
	strVar += "}";
	strVar += ".wrapper .preheader {";
	strVar += "  width: 600px;";
	strVar += "}";
	strVar += ".wrapper .preheader table {";
	strVar += "  width: 540px;";
	strVar += "}";
	strVar += ".wrapper .preheader .inner {";
	strVar += "  padding-top: 11px;";
	strVar += "  padding-bottom: 12px;";
	strVar += "}";
	strVar += ".wrapper .preheader .title {";
	strVar += "  text-align: left;";
	strVar += "}";
	strVar += ".wrapper .preheader .webversion {";
	strVar += "  text-align: right;";
	strVar += "  width: 240px;";
	strVar += "}";
	strVar += ".wrapper .preheader .webversion a {";
	strVar += "  letter-spacing: 0.03em;";
	strVar += "}";
	strVar += ".wrapper .preheader .title a,";
	strVar += ".wrapper .preheader .webversion a {";
	strVar += "  font-weight: bold;";
	strVar += "  text-decoration: none;";
	strVar += "}";
	strVar += ".wrapper h1 a,";
	strVar += ".wrapper h2 a,";
	strVar += ".wrapper h3 a {";
	strVar += "  text-decoration: none;";
	strVar += "}";
	strVar += ".wrapper h1 {";
	strVar += "  font-size: 36px;";
	strVar += "  Margin-bottom: 21px;";
	strVar += "  text-align: center;";
	strVar += "}";
	strVar += ".wrapper h2 {";
	strVar += "  font-size: 24px;";
	strVar += "  Margin-bottom: 20px;";
	strVar += "}";
	strVar += ".wrapper h3 {";
	strVar += "  font-size: 15px;";
	strVar += "  Margin-bottom: 16px;";
	strVar += "}";
	strVar += ".wrapper p,";
	strVar += ".wrapper ol,";
	strVar += ".wrapper ul {";
	strVar += "  font-size: 15px;";
	strVar += "}";
	strVar += ".wrapper p a,";
	strVar += ".wrapper ol a,";
	strVar += ".wrapper ul a {";
	strVar += "  text-decoration: none;";
	strVar += "}";
	strVar += ".wrapper p a:hover,";
	strVar += ".wrapper ol a:hover,";
	strVar += ".wrapper ul a:hover {";
	strVar += "  border-bottom: none !important;";
	strVar += "}";
	strVar += ".wrapper ol,";
	strVar += ".wrapper ul {";
	strVar += "  Margin-left: 39px;";
	strVar += "}";
	strVar += ".wrapper blockquote {";
	strVar += "  Margin-left: 1em;";
	strVar += "  padding-left: 1em;";
	strVar += "}";
	strVar += ".wrapper .btn {";
	strVar += "  Margin-bottom: 25px;";
	strVar += "}";
	strVar += ".wrapper .btn a {";
	strVar += "  background-image: url(https:\/\/i1.createsend1.com\/static\/eb\/master\/02-blush\/images\/btn-one-col.png);";
	strVar += "  background-position: center center;";
	strVar += "  background-size: cover;";
	strVar += "  display: inline-block;";
	strVar += "  font-size: 15px;";
	strVar += "  font-weight: 400;";
	strVar += "  line-height: 25px;";
	strVar += "  padding: 8px 24px 9px 24px;";
	strVar += "  text-align: center;";
	strVar += "  text-decoration: none;";
	strVar += "  transition: all .2s;";
	strVar += "  width: 432px;";
	strVar += "}";
	strVar += ".wrapper .btn a:hover {";
	strVar += "  opacity: .9;";
	strVar += "}";
	strVar += ".preheader .title,";
	strVar += ".preheader .webversion,";
	strVar += ".footer .padded {";
	strVar += "  font-size: 11px;";
	strVar += "  font-weight: normal;";
	strVar += "  letter-spacing: 0.01em;";
	strVar += "  line-height: 17px;";
	strVar += "}";
	strVar += ".two-col .column table:nth-last-child(2) td h1:last-child,";
	strVar += ".two-col .column table:nth-last-child(2) td h2:last-child,";
	strVar += ".two-col .column table:nth-last-child(2) td h3:last-child,";
	strVar += ".two-col .column table:nth-last-child(2) td p:last-child,";
	strVar += ".two-col .column table:nth-last-child(2) td ol:last-child,";
	strVar += ".two-col .column table:nth-last-child(2) td ul:last-child {";
	strVar += "  Margin-bottom: 23px;";
	strVar += "}";
	strVar += ".two-col h1 {";
	strVar += "  font-size: 32px;";
	strVar += "  Margin-bottom: 18px;";
	strVar += "}";
	strVar += ".two-col h2 {";
	strVar += "  font-size: 20px;";
	strVar += "  Margin-bottom: 16px;";
	strVar += "}";
	strVar += ".two-col h3 {";
	strVar += "  font-size: 14px;";
	strVar += "  Margin-bottom: 14px;";
	strVar += "}";
	strVar += ".two-col p,";
	strVar += ".two-col ol,";
	strVar += ".two-col ul {";
	strVar += "  font-size: 14px;";
	strVar += "}";
	strVar += ".two-col ol,";
	strVar += ".two-col ul {";
	strVar += "  Margin-left: 32px;";
	strVar += "}";
	strVar += ".two-col center.divider {";
	strVar += "  Margin-bottom: 23px;";
	strVar += "}";
	strVar += ".two-col .btn {";
	strVar += "  Margin-bottom: 23px;";
	strVar += "}";
	strVar += ".two-col .btn a {";
	strVar += "  background-image: url(https:\/\/i2.createsend1.com\/static\/eb\/master\/02-blush\/images\/btn-two-col.png);";
	strVar += "  font-size: 14px;";
	strVar += "  line-height: 23px;";
	strVar += "  padding: 7px 24px 8px 24px;";
	strVar += "  width: 162px;";
	strVar += "}";
	strVar += ".three-col .column table:nth-last-child(2) td h1:last-child,";
	strVar += ".three-col .column table:nth-last-child(2) td h2:last-child,";
	strVar += ".three-col .column table:nth-last-child(2) td h3:last-child,";
	strVar += ".three-col .column table:nth-last-child(2) td p:last-child,";
	strVar += ".three-col .column table:nth-last-child(2) td ol:last-child,";
	strVar += ".three-col .column table:nth-last-child(2) td ul:last-child {";
	strVar += "  Margin-bottom: 21px;";
	strVar += "}";
	strVar += ".three-col h1 {";
	strVar += "  background-image: none;";
	strVar += "  font-size: 26px;";
	strVar += "  Margin-bottom: 16px;";
	strVar += "}";
	strVar += ".three-col h2 {";
	strVar += "  font-size: 18px;";
	strVar += "  Margin-bottom: 12px;";
	strVar += "}";
	strVar += ".three-col h3 {";
	strVar += "  font-size: 13px;";
	strVar += "  Margin-bottom: 10px;";
	strVar += "}";
	strVar += ".three-col p,";
	strVar += ".three-col ol,";
	strVar += ".three-col ul {";
	strVar += "  font-size: 13px;";
	strVar += "}";
	strVar += ".three-col ol,";
	strVar += ".three-col ul {";
	strVar += "  Margin-left: 24px;";
	strVar += "}";
	strVar += ".three-col center.divider {";
	strVar += "  Margin-bottom: 21px;";
	strVar += "}";
	strVar += ".three-col .btn {";
	strVar += "  Margin-bottom: 21px;";
	strVar += "}";
	strVar += ".three-col .btn a {";
	strVar += "  background-image: url(https:\/\/i4.createsend1.com\/static\/eb\/master\/02-blush\/images\/btn-three-col.png);";
	strVar += "  font-size: 13px;";
	strVar += "  line-height: 21px;";
	strVar += "  padding: 5px 24px 6px 24px;";
	strVar += "  width: 92px;";
	strVar += "}";
	strVar += ".feature-top,";
	strVar += ".feature-bottom {";
	strVar += "  background-color: #ffffff;";
	strVar += "  font-size: 0;";
	strVar += "  line-height: 0;";
	strVar += "  width: 600px;";
	strVar += "}";
	strVar += ".feature-top img,";
	strVar += ".feature-bottom img {";
	strVar += "  display: inline-block;";
	strVar += "}";
	strVar += ".feature-top {";
	strVar += "  padding-bottom: 44px;";
	strVar += "}";
	strVar += ".feature-bottom {";
	strVar += "  padding-top: 31px;";
	strVar += "}";
	strVar += ".feature {";
	strVar += "  background-color: #ffffff;";
	strVar += "  width: 600px;";
	strVar += "}";
	strVar += ".feature .column-top {";
	strVar += "  font-size: 44px;";
	strVar += "  line-height: 44px;";
	strVar += "}";
	strVar += ".feature .column-bottom {";
	strVar += "  font-size: 10px;";
	strVar += "  line-height: 10px;";
	strVar += "}";
	strVar += ".feature .one-col {";
	strVar += "  text-align: center;";
	strVar += "  width: 510px;";
	strVar += "}";
	strVar += ".wrapper .feature .one-col {";
	strVar += "  box-shadow: none;";
	strVar += "}";
	strVar += ".feature .padded {";
	strVar += "  padding-left: 44px;";
	strVar += "  padding-right: 44px;";
	strVar += "}";
	strVar += ".feature h2 {";
	strVar += "  text-align: center;";
	strVar += "}";
	strVar += ".feature h3 {";
	strVar += "  text-align: center;";
	strVar += "}";
	strVar += ".feature p {";
	strVar += "  text-align: center;";
	strVar += "}";
	strVar += ".feature ol,";
	strVar += ".feature ul {";
	strVar += "  text-align: left;";
	strVar += "}";
	strVar += ".feature blockquote {";
	strVar += "  border-left: 0;";
	strVar += "  Margin-left: 0;";
	strVar += "  padding-left: 0;";
	strVar += "}";
	strVar += ".wrapper .feature .btn a {";
	strVar += "  background-image: url(https:\/\/i3.createsend1.com\/static\/eb\/master\/02-blush\/images\/btn-feature.png);";
	strVar += "  width: 372px;";
	strVar += "}";
	strVar += ".frame-bottom td {";
	strVar += "  line-height: 9px;";
	strVar += "}";
	strVar += ".frame-bottom .left,";
	strVar += ".frame-bottom .right {";
	strVar += "  width: 245px;";
	strVar += "}";
	strVar += ".heart {";
	strVar += "  mso-line-height-rule: at-least;";
	strVar += "  vertical-align: middle;";
	strVar += "  width: 18px;";
	strVar += "}";
	strVar += ".heart img {";
	strVar += "  display: block;";
	strVar += "}";
	strVar += ".header {";
	strVar += "  width: 600px;";
	strVar += "}";
	strVar += ".logo {";
	strVar += "  padding-top: 40px;";
	strVar += "  padding-bottom: 37px;";
	strVar += "}";
	strVar += ".logo div {";
	strVar += "  font-size: 42px;";
	strVar += "  line-height: 50px;";
	strVar += "}";
	strVar += ".logo div a {";
	strVar += "  text-decoration: none;";
	strVar += "}";
	strVar += ".logo div.logo-center {";
	strVar += "  text-align: center;";
	strVar += "}";
	strVar += ".logo div.logo-center img {";
	strVar += "  Margin-left: auto;";
	strVar += "  Margin-right: auto;";
	strVar += "}";
	strVar += ".footer {";
	strVar += "  width: 600px;";
	strVar += "}";
	strVar += ".footer .divider {";
	strVar += "  line-height: 11px;";
	strVar += "  width: 100%;";
	strVar += "}";
	strVar += ".footer #address a,";
	strVar += ".footer #permission a {";
	strVar += "  text-decoration: none;";
	strVar += "  font-weight: normal;";
	strVar += "}";
	strVar += ".social td {";
	strVar += "  padding: 0 13px 40px 13px;";
	strVar += "  vertical-align: middle;";
	strVar += "}";
	strVar += ".social img {";
	strVar += "  vertical-align: middle;";
	strVar += "}";
	strVar += ".social span {";
	strVar += "  mso-text-raise: 6px;";
	strVar += "}";
	strVar += ".forward,";
	strVar += ".facebook,";
	strVar += ".twitter {";
	strVar += "  display: inline-block;";
	strVar += "  font-size: 12px;";
	strVar += "  font-weight: 400;";
	strVar += "  line-height: 12px;";
	strVar += "  text-decoration: none;";
	strVar += "  text-transform: uppercase;";
	strVar += "}";
	strVar += ".footer .contents {";
	strVar += "  width: 600px;";
	strVar += "}";
	strVar += ".footer .contents a {";
	strVar += "  font-weight: 700;";
	strVar += "  text-decoration: none;";
	strVar += "}";
	strVar += ".address,";
	strVar += ".campaign {";
	strVar += "  font-size: 11px;";
	strVar += "  font-weight: 400;";
	strVar += "  line-height: 19px;";
	strVar += "  padding-bottom: 40px;";
	strVar += "  -webkit-font-smoothing: antialiased;";
	strVar += "}";
	strVar += ".address {";
	strVar += "  text-align: left;";
	strVar += "  padding-left: 30px;";
	strVar += "  padding-right: 10px;";
	strVar += "  width: 45%;";
	strVar += "}";
	strVar += ".campaign {";
	strVar += "  text-align: right;";
	strVar += "  padding-right: 30px;";
	strVar += "  padding-left: 10px;";
	strVar += "  width: 55%;";
	strVar += "}";
	strVar += ".campaign .links a {";
	strVar += "  font-weight: bold;";
	strVar += "}";
	strVar += ".column .rounded-image-bleed:first-child .gnd-corner-image-top.gnd-corner-image-center {";
	strVar += "  border-top-left-radius: 4px;";
	strVar += "  -moz-border-top-left-radius: 4px;";
	strVar += "  border-top-right-radius: 4px;";
	strVar += "  -moz-border-top-right-radius: 4px;";
	strVar += "}";
	strVar += ".column .rounded-image-bleed:first-child .gnd-corner-image-top.gnd-corner-image-left {";
	strVar += "  border-top-left-radius: 4px;";
	strVar += "  -moz-border-top-left-radius: 4px;";
	strVar += "  border-top-right-radius: 0;";
	strVar += "  -moz-border-top-right-radius: 0;";
	strVar += "}";
	strVar += ".column .rounded-image-bleed:first-child .gnd-corner-image-top.gnd-corner-image-right {";
	strVar += "  border-top-left-radius: 0;";
	strVar += "  -moz-border-top-left-radius: 0;";
	strVar += "  border-top-right-radius: 4px;";
	strVar += "  -moz-border-top-right-radius: 4px;";
	strVar += "}";
	strVar += ".first.column .rounded-image-bleed:first-child .gnd-corner-image-top.gnd-corner-image-center,";
	strVar += ".first.column .rounded-image-bleed:first-child .gnd-corner-image-top.gnd-corner-image-left {";
	strVar += "  border-top-left-radius: 4px;";
	strVar += "  -moz-border-top-left-radius: 4px;";
	strVar += "  border-top-right-radius: 0;";
	strVar += "  -moz-border-top-right-radius: 0;";
	strVar += "}";
	strVar += ".two-col .second.column .rounded-image-bleed:first-child .gnd-corner-image-top.gnd-corner-image-center,";
	strVar += ".two-col .second.column .rounded-image-bleed:first-child .gnd-corner-image-top.gnd-corner-image-right {";
	strVar += "  border-top-left-radius: 0;";
	strVar += "  -moz-border-top-left-radius: 0;";
	strVar += "  border-top-right-radius: 4px;";
	strVar += "  -moz-border-top-right-radius: 4px;";
	strVar += "}";
	strVar += ".three-col .second.column .rounded-image-bleed:first-child .gnd-corner-image-top.gnd-corner-image-center,";
	strVar += ".three-col .second.column .rounded-image-bleed:first-child .gnd-corner-image-top.gnd-corner-image-right,";
	strVar += ".three-col .second.column .rounded-image-bleed:first-child .gnd-corner-image-top.gnd-corner-image-left {";
	strVar += "  border-top-left-radius: 0;";
	strVar += "  -moz-border-top-left-radius: 0;";
	strVar += "  border-top-right-radius: 0;";
	strVar += "  -moz-border-top-right-radius: 0;";
	strVar += "}";
	strVar += ".third.column .rounded-image-bleed:first-child .gnd-corner-image-top.gnd-corner-image-center,";
	strVar += ".third.column .rounded-image-bleed:first-child .gnd-corner-image-top.gnd-corner-image-right {";
	strVar += "  border-top-left-radius: 0;";
	strVar += "  -moz-border-top-left-radius: 0;";
	strVar += "  border-top-right-radius: 4px;";
	strVar += "  -moz-border-top-right-radius: 4px;";
	strVar += "}";
	strVar += "@media only screen and (max-width: 620px) {";
	strVar += "  [class=wrapper] .preheader,";
	strVar += "  [class=wrapper] .preheader table,";
	strVar += "  [class=wrapper] .header,";
	strVar += "  [class=wrapper] .footer,";
	strVar += "  [class=wrapper] .footer .contents,";
	strVar += "  [class=wrapper] .feature {";
	strVar += "    width: 320px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .preheader .title {";
	strVar += "    display: none;";
	strVar += "  }";
	strVar += "  [class=wrapper] .preheader .webversion {";
	strVar += "    text-align: center !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .logo {";
	strVar += "    padding-left: 10px !important;";
	strVar += "    padding-right: 10px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .logo img {";
	strVar += "    max-width: 280px !important;";
	strVar += "    height: auto !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .footer .address,";
	strVar += "  [class=wrapper] .footer .campaign {";
	strVar += "    display: block;";
	strVar += "    padding-left: 30px !important;";
	strVar += "    padding-right: 30px !important;";
	strVar += "    text-align: center !important;";
	strVar += "    width: 260px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .footer .address {";
	strVar += "    padding-bottom: 20px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .footer .social td {";
	strVar += "    display: block !important;";
	strVar += "    text-align: center !important;";
	strVar += "    padding-left: 0 !important;";
	strVar += "    padding-right: 0 !important;";
	strVar += "    padding-bottom: 10px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .footer .social td:last-child {";
	strVar += "    padding-bottom: 40px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .first .column-bottom,";
	strVar += "  [class=wrapper] .three-col .second .column-bottom {";
	strVar += "    display: none;";
	strVar += "  }";
	strVar += "  [class=wrapper] .second .column-top,";
	strVar += "  [class=wrapper] .third .column-top {";
	strVar += "    display: none;";
	strVar += "  }";
	strVar += "  [class=wrapper] .one-col .column:last-child table:nth-last-child(2) td h1:last-child,";
	strVar += "  [class=wrapper] .two-col .column:last-child table:nth-last-child(2) td h1:last-child,";
	strVar += "  [class=wrapper] .three-col .column:last-child table:nth-last-child(2) td h1:last-child,";
	strVar += "  [class=wrapper] .one-col .column:last-child table:nth-last-child(2) td h2:last-child,";
	strVar += "  [class=wrapper] .two-col .column:last-child table:nth-last-child(2) td h2:last-child,";
	strVar += "  [class=wrapper] .three-col .column:last-child table:nth-last-child(2) td h2:last-child,";
	strVar += "  [class=wrapper] .one-col .column:last-child table:nth-last-child(2) td h3:last-child,";
	strVar += "  [class=wrapper] .two-col .column:last-child table:nth-last-child(2) td h3:last-child,";
	strVar += "  [class=wrapper] .three-col .column:last-child table:nth-last-child(2) td h3:last-child,";
	strVar += "  [class=wrapper] .one-col .column:last-child table:nth-last-child(2) td p:last-child,";
	strVar += "  [class=wrapper] .two-col .column:last-child table:nth-last-child(2) td p:last-child,";
	strVar += "  [class=wrapper] .three-col .column:last-child table:nth-last-child(2) td p:last-child,";
	strVar += "  [class=wrapper] .one-col .column:last-child table:nth-last-child(2) td ol:last-child,";
	strVar += "  [class=wrapper] .two-col .column:last-child table:nth-last-child(2) td ol:last-child,";
	strVar += "  [class=wrapper] .three-col .column:last-child table:nth-last-child(2) td ol:last-child,";
	strVar += "  [class=wrapper] .one-col .column:last-child table:nth-last-child(2) td ul:last-child,";
	strVar += "  [class=wrapper] .two-col .column:last-child table:nth-last-child(2) td ul:last-child,";
	strVar += "  [class=wrapper] .three-col .column:last-child table:nth-last-child(2) td ul:last-child {";
	strVar += "    Margin-bottom: 25px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .column-top {";
	strVar += "    font-size: 25px !important;";
	strVar += "    line-height: 25px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .column-bottom {";
	strVar += "    font-size: 5px !important;";
	strVar += "    line-height: 5px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] center.divider {";
	strVar += "    margin-bottom: 25px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .btn {";
	strVar += "    margin-bottom: 25px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .btn a {";
	strVar += "    background-image: url(https:\/\/i5.createsend1.com\/static\/eb\/master\/02-blush\/images\/btn-mobile.png) !important;";
	strVar += "    display: block !important;";
	strVar += "    font-size: 15px !important;";
	strVar += "    line-height: 25px !important;";
	strVar += "    padding: 8px 24px 9px 24px !important;";
	strVar += "    width: auto !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] h1 {";
	strVar += "    font-size: 36px !important;";
	strVar += "    margin-bottom: 21px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] h2 {";
	strVar += "    font-size: 24px !important;";
	strVar += "    margin-bottom: 20px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] h3 {";
	strVar += "    font-size: 15px !important;";
	strVar += "    margin-bottom: 16px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .one-col p,";
	strVar += "  [class=wrapper] .two-col p,";
	strVar += "  [class=wrapper] .three-col p,";
	strVar += "  [class=wrapper] .one-col ol,";
	strVar += "  [class=wrapper] .two-col ol,";
	strVar += "  [class=wrapper] .three-col ol,";
	strVar += "  [class=wrapper] .one-col ul,";
	strVar += "  [class=wrapper] .two-col ul,";
	strVar += "  [class=wrapper] .three-col ul {";
	strVar += "    font-size: 15px !important;";
	strVar += "    line-height: 25px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] ol,";
	strVar += "  [class=wrapper] ul {";
	strVar += "    margin-left: 26px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .feature-top {";
	strVar += "    padding-bottom: 25px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .feature-bottom {";
	strVar += "    padding-top: 9px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .feature-top img,";
	strVar += "  [class=wrapper] .feature-bottom img {";
	strVar += "    display: block !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .feature-top .right,";
	strVar += "  [class=wrapper] .feature-bottom .right {";
	strVar += "    display: none !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .feature .one-col,";
	strVar += "  [class=wrapper] .feature .column {";
	strVar += "    width: 280px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .feature .padded {";
	strVar += "    padding-left: 20px !important;";
	strVar += "    padding-right: 20px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .feature .column-top {";
	strVar += "    font-size: 20px !important;";
	strVar += "    line-height: 20px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .feature .column-bottom {";
	strVar += "    font-size: 2px !important;";
	strVar += "    line-height: 2px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .feature .frame-bottom .left,";
	strVar += "  [class=wrapper] .feature .frame-bottom .right {";
	strVar += "    width: 131px !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .feature .btn a {";
	strVar += "    background-image: url(https:\/\/i7.createsend1.com\/static\/eb\/master\/02-blush\/images\/btn-feature-mobile.png) !important;";
	strVar += "  }";
	strVar += "}";
	strVar += "@media only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min--moz-device-pixel-ratio: 2), only screen and (-o-min-device-pixel-ratio: 2\/1), only screen and (min-device-pixel-ratio: 2), only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) {";
	strVar += "  [class=wrapper] .one-col .btn a {";
	strVar += "    background-image: url(https:\/\/i6.createsend1.com\/static\/eb\/master\/02-blush\/images\/btn-one-col-2x.png) !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .two-col .btn a {";
	strVar += "    background-image: url(https:\/\/i8.createsend1.com\/static\/eb\/master\/02-blush\/images\/btn-two-col-2x.png) !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .three-col .btn a {";
	strVar += "    background-image: url(https:\/\/i9.createsend1.com\/static\/eb\/master\/02-blush\/images\/btn-three-col-2x.png) !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .feature .btn a {";
	strVar += "    background-image: url(https:\/\/i1.createsend1.com\/static\/eb\/master\/02-blush\/images\/btn-feature-2x.png) !important;";
	strVar += "  }";
	strVar += "}";
	strVar += "@media only screen and (max-width: 620px) and (-webkit-min-device-pixel-ratio: 2), only screen and (max-width: 620px) and (min--moz-device-pixel-ratio: 2), only screen and (max-width: 620px) and (-o-min-device-pixel-ratio: 2\/1), only screen and (max-width: 620px) and (min-device-pixel-ratio: 2), only screen and (max-width: 620px) and (min-resolution: 192dpi), only screen and (max-width: 620px) and (min-resolution: 2dppx) {";
	strVar += "  [class=wrapper] .btn a {";
	strVar += "    background-image: url(https:\/\/i10.createsend1.com\/static\/eb\/master\/02-blush\/images\/btn-mobile-2x.png) !important;";
	strVar += "  }";
	strVar += "  [class=wrapper] .feature .btn a {";
	strVar += "    background-image: url(https:\/\/i2.createsend1.com\/static\/eb\/master\/02-blush\/images\/btn-feature-mobile-2x.png) !important;";
	strVar += "  }";
	strVar += "}";
	strVar += "@media only screen and (-webkit-min-device-pixel-ratio: 1) {";
	strVar += "  .divider img,";
	strVar += "  .heart img {";
	strVar += "    outline: 1px solid #ffffff;";
	strVar += "  }";
	strVar += "  .feature-top img,";
	strVar += "  .feature-bottom img {";
	strVar += "    float: left;";
	strVar += "  }";
	strVar += "}";
	strVar += "<\/style>";
	strVar += "    <!--[if mso]>";
	strVar += "    <style>";
	strVar += "      .frame-bottom .left, .frame-bottom .right {";
	strVar += "        width: 246px !important;";
	strVar += "      }";
	strVar += "      .column-top {";
	strVar += "        mso-line-height-rule: exactly !important;";
	strVar += "      }";
	strVar += "    <\/style>";
	strVar += "    <![endif]-->";
	strVar += "  <meta name=\"robots\" content=\"noindex,nofollow\">";
	strVar += "<meta property=\"og:title\" content=\"My First Campaign\">";
	strVar += "<\/head>";
	strVar += "  <body style=\"margin: 0;mso-line-height-rule: exactly;padding: 0;min-width: 100%;background-color: #fff\"><style type=\"text\/css\">";
	strVar += "@import url(https:\/\/fonts.googleapis.com\/css?family=Lato:400,700,400italic,700italic);@import url(https:\/\/fonts.googleapis.com\/css?family=Lato:400,700,400italic,700italic);@import url(https:\/\/fonts.googleapis.com\/css?family=Lato:400,700,400italic,700italic);@import url(https:\/\/fonts.googleapis.com\/css?family=Lato:400,700,400italic,700italic);@import url(https:\/\/fonts.googleapis.com\/css?family=Lato:400,700,400italic,700italic);@import url(https:\/\/fonts.googleapis.com\/css?family=Roboto:400,700,400italic,700italic);body,.wrapper,.separator,.emb-editor-canvas{background-color:#fff}h1{color:#db1515}.wrapper h1{}.wrapper h1{font-family:Tahoma,sans-serif}@media only screen and (min-width: 0){.wrapper h1{font-family:Lato,Tahoma,sans-serif !important}}h1{}.one-col h1{line-height:44px}.two-col h1{line-height:38px}.three-col h1{line-height:32px}@media only screen and (max-width: ";
	strVar += "620px){h1{line-height:44px !important}}h2{color:#555}.wrapper h2{}.wrapper h2{font-family:Tahoma,sans-serif}@media only screen and (min-width: 0){.wrapper h2{font-family:Lato,Tahoma,sans-serif !important}}h2{}.one-col h2{line-height:32px}.two-col h2{line-height:26px}.three-col h2{line-height:24px}@media only screen and (max-width: 620px){h2{line-height:32px !important}}h3{color:#555}.wrapper h3{}.wrapper h3{font-family:Tahoma,sans-serif}@media only screen and (min-width: 0){.wrapper h3{font-family:Lato,Tahoma,sans-serif !important}}h3{}.one-col h3{line-height:23px}.two-col h3{line-height:20px}.three-col h3{line-height:19px}@media only screen and (max-width: 620px){h3{line-height:23px !important}}p,ol,ul{color:#61606c}.wrapper p,.wrapper ol,.wrapper ul{}.wrapper p,.wrapper ol,.wrapper ul{font-family:Tahoma,sans-serif}@media only screen and (min-width: 0){.wrapper p,.wrapper ol,.wrapper ";
	strVar += "ul{font-family:Lato,Tahoma,sans-serif !important}}p,ol,ul{}.one-col p,.one-col ol,.one-col ul{line-height:24px;Margin-bottom:24px}.two-col p,.two-col ol,.two-col ul{line-height:22px;Margin-bottom:22px}.three-col p,.three-col ol,.three-col ul{line-height:21px;Margin-bottom:21px}@media only screen and (max-width: 620px){p,ol,ul{line-height:24px !important;Margin-bottom:24px !important}}.image{color:#61606c}.image{font-family:Tahoma,sans-serif}@media only screen and (min-width: 0){.image{font-family:Lato,Tahoma,sans-serif !important}}.wrapper a{color:#41637e}.wrapper a:hover{color:#30495c !important}.wrapper p a,.wrapper ol a,.wrapper ul a{border-bottom:1px dotted #41637e}.wrapper p a:hover,.wrapper ol a:hover,.wrapper ul a:hover{border-bottom-color:#30495c !important}.wrapper .logo div{color:#555}.wrapper .logo div{font-family:Tahoma,sans-serif}@media only screen and (min-width: ";
	strVar += "0){.wrapper .logo div{font-family:Roboto,Tahoma,sans-serif !important}}.wrapper .logo div a{color:#555}.wrapper .logo div a:hover{color:#555 !important}.btn a{}.wrapper .btn a{}.wrapper .btn a{font-family:Tahoma,sans-serif}@media only screen and (min-width: 0){.wrapper .btn a{font-family:Lato,Tahoma,sans-serif !important}}.wrapper .btn a{background-color:#db1515;border-top:1px solid #f37d7d;border-bottom:1px solid #950e0e;color:#fff !important;text-shadow:0 1px 0 0 1px 0 #c51313}.wrapper .btn a:hover{background-color:#ee4e4e !important;color:#fff !important}blockquote{border-left:4px solid #fff}center.divider span,center.divider img{background-color:#db1515}.feature .one-col{border-top:1px dashed #db1515;border-left:1px dashed #db1515;border-right:1px dashed #db1515}.frame-bottom .left,.frame-bottom .right{border-bottom:1px dashed #db1515;mso-border-bottom-alt:1pt dashed ";
	strVar += "#db1515}.frame-bottom .left{border-left:1px dashed #db1515;mso-border-left-alt:1pt dashed #db1515}.frame-bottom .right{border-right:1px dashed #db1515;mso-border-right-alt:1pt dashed #db1515}.heart span,.heart img{background-color:#db1515}.feature-top span,.feature-bottom span,.feature-top img,.feature-bottom img{background-color:#fff}.header{border-top:1px dashed #b3b3b3}.footer .forward,.footer .facebook,.footer .twitter{color:#b3b3b3}.wrapper .footer .forward,.wrapper .footer .facebook,.wrapper .footer .twitter{}.wrapper .footer .forward,.wrapper .footer .facebook,.wrapper .footer .twitter{font-family:Tahoma,sans-serif}@media only screen and (min-width: 0){.wrapper .footer .forward,.wrapper .footer .facebook,.wrapper .footer .twitter{font-family:Lato,Tahoma,sans-serif !important}}.footer .forward,.footer .facebook,.footer .twitter{}.footer .forward,.footer .facebook,.footer ";
	strVar += ".twitter{letter-spacing:0.05em}.footer .forward:hover,.footer .facebook:hover,.footer .twitter:hover{color:#8d8d8d !important}.address,.campaign,.preheader .title,.preheader .webversion{color:#b3b3b3}.address,.campaign,.preheader .title,.preheader .webversion{font-family:Tahoma,sans-serif}@media only screen and (min-width: 0){.address,.campaign,.preheader .title,.preheader .webversion{font-family:Lato,Tahoma,sans-serif !important}}.wrapper .address a,.wrapper .campaign a,.wrapper .preheader .title a,.wrapper .preheader .webversion a{color:#b3b3b3}.wrapper .address a:hover,.wrapper .campaign a:hover,.wrapper .preheader .title a:hover,.wrapper .preheader .webversion a:hover{color:#8d8d8d !important}.footer .campaign a{}.wrapper .footer .campaign a{}.wrapper .footer .campaign a{font-family:Tahoma,sans-serif}@media only screen and (min-width: 0){.wrapper .footer .campaign ";
	strVar += "a{font-family:Lato,Tahoma,sans-serif !important}}.footer .campaign a{}.footer .campaign a{letter-spacing:0.03em}.footer .divider{border-top:1px dashed #b3b3b3}.forward,.facebook,.twitter{}.wrapper .forward,.wrapper .facebook,.wrapper .twitter{}.wrapper .forward,.wrapper .facebook,.wrapper .twitter{font-family:Tahoma,sans-serif}@media only screen and (min-width: 0){.wrapper .forward,.wrapper .facebook,.wrapper .twitter{font-family:Lato,Tahoma,sans-serif !important}}.forward,.facebook,.twitter{}.forward,.facebook,.twitter{letter-spacing:0.05em}";
	strVar += "<\/style>";
	strVar += "    <center class=\"wrapper\" style=\"display: table;table-layout: fixed;width: 100%;min-width: 620px;-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;background-color: #fff\">";
	strVar += "      <table class=\"preheader centered\" style=\"border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;width: 600px\">";
	strVar += "        <tbody><tr>";
	strVar += "          <td class=\"inner\" style=\"padding: 0;vertical-align: top;padding-top: 11px;padding-bottom: 12px\">";
	strVar += "            <table style=\"border-collapse: collapse;border-spacing: 0;width: 540px;Margin-left: auto;Margin-right: auto\" align=\"center\">";
	strVar += "              <tbody><tr>";
	strVar += "                ";
	strVar += "                ";
	strVar += "              <\/tr>";
	strVar += "            <\/tbody><\/table>";
	strVar += "          <\/td>";
	strVar += "        <\/tr>";
	strVar += "      <\/tbody><\/table>";
	strVar += "      ";
	strVar += "      ";
	strVar += "          <table class=\"one-col centered\" style=\"border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;width: 600px;background-color: #ffffff;border-radius: 4px;box-shadow: 0 1px 0 rgba(0, 0, 0, 0.1);table-layout: fixed\">";
	strVar += "            <tbody><tr>";
	strVar += "              <td class=\"column\" style=\"padding: 0;vertical-align: top;text-align: left\">";
	strVar += "                <div><div class=\"column-top\" style=\"font-size: 60px;line-height: 60px\">&nbsp;<\/div><\/div>";
	strVar += "                  <table class=\"contents\" style=\"border-collapse: collapse;border-spacing: 0;table-layout: fixed;width: 100%\">";
	strVar += "                    <tbody><tr>";
	strVar += "                      <td class=\"padded\" style=\"padding: 0;vertical-align: top;padding-left: 60px;padding-right: 60px;word-break: break-word;word-wrap: break-word\">";
	strVar += "                        ";
	strVar += "            <center class=\"divider\" style=\"Margin-bottom: 25px\"><span style=\"background-color: #db1515\"><img style=\"border: 0;-ms-interpolation-mode: bicubic;background-color: #db1515;display: block;Margin-left: auto;Margin-right: auto\" src=\"https:\/\/i10.createsend1.com\/static\/eb\/master\/02-blush\/images\/waves.png\" width=\"32\" height=\"4\" alt=\"\"><\/span><\/center>";
	strVar += "          ";
	strVar += "                      <\/td>";
	strVar += "                    <\/tr>";
	strVar += "                  <\/tbody><\/table>";
	strVar += "                ";
	strVar += "                  <table class=\"contents\" style=\"border-collapse: collapse;border-spacing: 0;table-layout: fixed;width: 100%\">";
	strVar += "                    <tbody><tr>";
	strVar += "                      <td class=\"padded\" style=\"padding: 0;vertical-align: top;padding-left: 60px;padding-right: 60px;word-break: break-word;word-wrap: break-word\">";
	strVar += "                        ";
	strVar += "            <h1 style=\"Margin-top: 0;color: #db1515;font-weight: 400;font-size: 36px;Margin-bottom: 21px;text-align: center;font-family: Tahoma,sans-serif;line-height: 44px\">Touchbase | Verify<\/h1>";
	strVar += "          ";
	strVar += "                      <\/td>";
	strVar += "                    <\/tr>";
	strVar += "                  <\/tbody><\/table>";
	strVar += "                ";
	strVar += "                  <table class=\"contents\" style=\"border-collapse: collapse;border-spacing: 0;table-layout: fixed;width: 100%\">";
	strVar += "                    <tbody><tr>";
	strVar += "                      <td class=\"padded\" style=\"padding: 0;vertical-align: top;padding-left: 60px;padding-right: 60px;word-break: break-word;word-wrap: break-word\">";
	strVar += "                        ";
	strVar += "            <p style=\"Margin-top: 0;color: #61606c;font-weight: 400;font-size: 15px;font-family: Tahoma,sans-serif;line-height: 24px;Margin-bottom: 24px;text-align: center\">To keep our accounts safe and ensure that all users are properly identified so that everyone you interact with is truly who they say they are. Click below to verify your account, and be led to the login screen<\/p>";
	strVar += "          ";
	strVar += "                      <\/td>";
	strVar += "                    <\/tr>";
	strVar += "                  <\/tbody><\/table>";
	strVar += "                ";
	strVar += "                  <table class=\"contents\" style=\"border-collapse: collapse;border-spacing: 0;table-layout: fixed;width: 100%\">";
	strVar += "                    <tbody><tr>";
	strVar += "                      <td class=\"padded\" style=\"padding: 0;vertical-align: top;padding-left: 60px;padding-right: 60px;word-break: break-word;word-wrap: break-word\">";
	strVar += "                        ";
	strVar += "            <div class=\"btn\" style=\"Margin-bottom: 25px;text-align: left\">";
	strVar += "              <!--[if !mso]--><a style=\"transition: all .2s;color: #fff !important;background-image: url(https:\/\/i1.createsend1.com\/static\/eb\/master\/02-blush\/images\/btn-one-col.png);background-position: center center;background-size: cover;display: inline-block;font-size: 15px;font-weight: 400;line-height: 25px;padding: 8px 24px 9px 24px;text-align: center;text-decoration: none;width: 432px;font-family: Tahoma,sans-serif;background-color: #db1515;border-top: 1px solid #f37d7d;border-bottom: 1px solid #950e0e;text-shadow: 0 1px 0 0 1px 0 #c51313\" href=\"http:\/\/localhost:3000/api/verify/"+verifyModel.sessionID+"\" target=\"_blank\">Verify<\/a><!--[endif]-->";
	strVar += ("            <!--[if mso]><v:rect xmlns:v=\"urn:schemas-microsoft-com:vml\" href=\"http:\/\/localhost:3000/api/verify/"+verifyModel.sessionID+"\" style=\"width:480px\" fill=\"t\" stroke=\"f\"><v:fill type=\"tile\" src=\"https:\/\/i1.createsend1.com\/static\/eb\/master\/02-blush\/images\/btn-one-col.png\" color=\"#DB1515\" origin=\"-0.5,-0.5\" position=\"0.5,0.5\"><\/v:fill><v:shadow on=\"t\" type=\"double\" color=\"#F37D7D\" color2=\"#950E0E\" offset=\"0,-1px\" offset2=\"0,1px\"><\/v:shadow><v:textbox style=\"mso-fit-shape-to-text:t\" inset=\"0px,8px,0px,9px\"><center style=\"font-size:15px;line-height:25px;color:#FFFFFF;font-family:Tahoma,sans-serif;font-weight:400;mso-line-height-rule:exactly;mso-text-raise:4px\">Verify<\/center><\/v:textbox><\/v:rect><![endif]--><\/div>");
	strVar += "          ";
	strVar += "                      <\/td>";
	strVar += "                    <\/tr>";
	strVar += "                  <\/tbody><\/table>";
	strVar += "                ";
	strVar += "                  <table class=\"contents\" style=\"border-collapse: collapse;border-spacing: 0;table-layout: fixed;width: 100%\">";
	strVar += "                    <tbody><tr>";
	strVar += "                      <td class=\"padded\" style=\"padding: 0;vertical-align: top;padding-left: 60px;padding-right: 60px;word-break: break-word;word-wrap: break-word\">";
	strVar += "                        ";
	strVar += "            <center class=\"divider\" style=\"Margin-bottom: 25px\"><span style=\"background-color: #db1515\"><img style=\"border: 0;-ms-interpolation-mode: bicubic;background-color: #db1515;display: block;Margin-left: auto;Margin-right: auto\" src=\"https:\/\/i10.createsend1.com\/static\/eb\/master\/02-blush\/images\/waves.png\" width=\"32\" height=\"4\" alt=\"\"><\/span><\/center>";
	strVar += "          ";
	strVar += "                      <\/td>";
	strVar += "                    <\/tr>";
	strVar += "                  <\/tbody><\/table>";
	strVar += "                ";
	strVar += "                <div class=\"column-bottom\" style=\"font-size: 34px;line-height: 34px\">&nbsp;<\/div>";
	strVar += "              <\/td>";
	strVar += "            <\/tr>";
	strVar += "          <\/tbody><\/table>";
	strVar += "        ";
	strVar += "          ";
	strVar += "        ";
	strVar += "      <table class=\"footer centered\" style=\"border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;width: 600px\">";
	strVar += "        <tbody><tr>";
	strVar += "          <td style=\"padding: 0;vertical-align: top\">";
	strVar += "            ";
	strVar += "            <table class=\"divider\" style=\"border-collapse: collapse;border-spacing: 0;line-height: 11px;width: 100%;border-top: 1px dashed #b3b3b3\"><tbody><tr><td style=\"padding: 0;vertical-align: top\">&nbsp;<\/td><\/tr><\/tbody><\/table>";
	strVar += "            <table class=\"contents\" style=\"border-collapse: collapse;border-spacing: 0;table-layout: fixed;width: 600px\">";
	strVar += "              <tbody><tr>";
	strVar += "                <td class=\"address\" style=\"padding: 0;vertical-align: top;font-size: 11px;font-weight: 400;line-height: 19px;padding-bottom: 40px;-webkit-font-smoothing: antialiased;text-align: left;padding-left: 30px;padding-right: 10px;width: 45%;color: #b3b3b3;font-family: Tahoma,sans-serif\">";
	strVar += "                  <div>Couchbase | Mountain View, CA<\/div>";
	strVar += "                <\/td>";
	strVar += "                ";
	strVar += "              <\/tr>";
	strVar += "            <\/tbody><\/table>";
	strVar += "          <\/td>";
	strVar += "        <\/tr>";
	strVar += "      <\/tbody><\/table>";
	strVar += "    <\/center>";
	strVar += "  <img style=\"border: 0 !important;-ms-interpolation-mode: bicubic;visibility: hidden !important;display: block !important;height: 1px !important;width: 1px !important;margin: 0 !important;padding: 0 !important\" src=\"https:\/\/couchbase.createsend1.com\/t\/i-o-jiuhuid-l\/o.gif\" width=\"1\" height=\"1\" border=\"0\" alt=\"\">";
	strVar += "<script type=\"text\/javascript\" src=\"https:\/\/js.createsend1.com\/js\/jquery-1.7.2.min.js?h=C99A4659zeta\"><\/script><script type=\"text\/javascript\">$(function(){$('area,a').attr('target', '_blank');});<\/script>";
	strVar += "<\/body><\/html>";
	return strVar;
};

module.exports = Email;
